/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.dylantaylor.ttb;

public final class R {
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int tileSize=0x7f010000;
    }
    public static final class color {
        public static final int background=0x7f040000;
    }
    public static final class drawable {
        public static final int ball=0x7f020000;
        public static final int block=0x7f020001;
        public static final int bmmini=0x7f020002;
        public static final int brushedmetal=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int mball=0x7f020005;
    }
    public static final class id {
        public static final int about_button=0x7f060005;
        public static final int about_content=0x7f060000;
        public static final int easy_button=0x7f060001;
        public static final int exit_button=0x7f060006;
        public static final int hard_button=0x7f060003;
        public static final int insane_button=0x7f060004;
        public static final int medium_button=0x7f060002;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int about_label=0x7f050004;
        public static final int about_text=0x7f050007;
        public static final int about_title=0x7f050006;
        public static final int app_name=0x7f050000;
        public static final int credit_title=0x7f050002;
        public static final int easy_label=0x7f050008;
        public static final int exit_label=0x7f050005;
        public static final int hard_label=0x7f05000a;
        public static final int insane_label=0x7f05000b;
        public static final int main_title=0x7f050001;
        public static final int medium_label=0x7f050009;
        public static final int mode_lose_prefix=0x7f05000e;
        public static final int mode_lose_suffix=0x7f05000f;
        public static final int mode_pause=0x7f05000d;
        public static final int mode_ready=0x7f05000c;
        public static final int start_label=0x7f050003;
        public static final int ttb_layout_text_text=0x7f050010;
    }
    public static final class styleable {
        /** Attributes that can be used with a TileView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #TileView_tileSize com.dylantaylor.ttb:tileSize}</code></td><td></td></tr>
           </table>
           @see #TileView_tileSize
         */
        public static final int[] TileView = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link com.dylantaylor.ttb.R.attr#tileSize}
          attribute's value can be found in the {@link #TileView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:tileSize
        */
        public static final int TileView_tileSize = 0;
    };
}
